force-app/main/default/objects/Case/fields/Innova_Brand__c.field-meta.xml
<CustomField>
    <fullName>Innova_Brand__c</fullName>
    <label>Brand</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Innova_Region__c.field-meta.xml
<CustomField>
    <fullName>Innova_Region__c</fullName>
    <label>Region</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Zone__c/Time_Zone__c.object-meta.xml
<CustomObject>
    <label>Time Zone</label>
    <nameField>
        <displayFormat>TZ-{000}</displayFormat>
        <label>Time Zone Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Zone__c/fields/Time_Zone_Name__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone_Name__c</fullName>
    <label>Time Zone Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Innova_Brand__c.field-meta.xml
<CustomField>
    <fullName>Innova_Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Innova Solutions</fullName>
            </value>
            <value>
                <fullName>HireGenics</fullName>
            </value>
            <value>
                <fullName>Volt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Innova_Region__c.field-meta.xml
<CustomField>
    <fullName>Innova_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC (India)</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>EMEA (Europe)</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
                <isActive>false</isActive>
                <label>UK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Europe - Belgium, France</fullName>
            </value>
            <value>
                <fullName>Europe - Eastern</fullName>
                <isActive>false</isActive>
                <label>Europe - Eastern</label>
            </value>
            <value>
                <fullName>Europe - GMT</fullName>
                <isActive>false</isActive>
                <label>Europe - GMT</label>
            </value>
            <value>
                <fullName>Europe - UK</fullName>
            </value>
            <value>
                <fullName>Europe - Western</fullName>
                <isActive>false</isActive>
                <label>Europe - Western</label>
            </value>
            <value>
                <fullName>India - Standard</fullName>
            </value>
            <value>
                <fullName>Mexico - Central</fullName>
            </value>
            <value>
                <fullName>Mexico - Eastern</fullName>
            </value>
            <value>
                <fullName>Mexico - Mountain</fullName>
            </value>
            <value>
                <fullName>Mexico - Pacific</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Taipei</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>USA / Canada - Central</fullName>
            </value>
            <value>
                <fullName>USA / Canada - Eastern</fullName>
            </value>
            <value>
                <fullName>USA / Canada - Mountain</fullName>
            </value>
            <value>
                <fullName>USA / Canada - Pacific</fullName>
            </value>
            <value>
                <fullName>USA - Hawaii</fullName>
            </value>
            <value>
                <fullName>USA - Phoenix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Unique_Auto_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_Auto_ID__c</fullName>
    <displayFormat>Inn-{0000}</displayFormat>
    <label>Unique Auto ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/CommunityDetailsCheckController.cls
public with sharing class CommunityDetailsCheckController {  
      
    /*
    @AuraEnabled( cacheable = true )
    public static List<String> getTimeZoneOptions(){
        
        List<String> timeZoneOptions = new List<String>();
        
        // Query the custom object 'Time_Zone__c' for picklist values
        List<Time_Zone__c> timeZones = [SELECT Time_Zone_Name__c FROM Time_Zone__c ORDER BY Time_Zone_Name__c];
        
        for (Time_Zone__c timeZone : timeZones) {
            timeZoneOptions.add(timeZone.Time_Zone_Name__c);
        }
        
        return timeZoneOptions;
        
    } */
   
    
    @AuraEnabled( cacheable = true )    
    public static User fetchInfo() { 
        
        User objUser;
        Id userId = System.UserInfo.getUserId();
        String EXPECTED_EXPECTION = 'List has no rows for assignment to SObject';
        String DOESNOTEXIST = 'does not exist';
        String QUERY_TEST = 'SELECT Id FROM User WHERE Name =:DOESNOTEXIST LIMIT 1';
        String QUERY_USER = 'SELECT Innova_Region__c,Innova_Brand__c,Time_Zone__c,Unique_Auto_ID__c  FROM User WHERE Id =:userId LIMIT 1';
        
        try{
          
            if(System.Test.isRunningTest()){
                objUser = Database.Query(QUERY_TEST);
                } else {
                    objUser = Database.Query(QUERY_USER); 
            	}
        
            return objUser;
            
            }
        catch (QueryException e) {
            if (e.getMessage().contains(EXPECTED_EXPECTION)) {
                // Handle the case where no user is found with the provided ID
                return null;
            }
            throw new AuraHandledException('Error fetching user details: ' + e.getMessage());
        }
         }

}