force-app/main/default/objects/Innova_Application_Software__c/Innova_Application_Software__c.object-meta.xml
<CustomObject>
    <label>Applications/Software</label>
    <nameField>
        <label>Applications/Software Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications/Software</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Innova_Access_Level__c</fullName>
    <label>Access Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Add__c.field-meta.xml
<CustomField>
    <fullName>Innova_Add__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Brand__c.field-meta.xml
<CustomField>
    <fullName>Innova_Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hiregenics</fullName>
                <label>HireGenics</label>
            </value>
            <value>
                <fullName>Innova Solutions</fullName>
            </value>
            <value>
                <fullName>Volt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Delete__c.field-meta.xml
<CustomField>
    <fullName>Innova_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Description_of_the_Request__c.field-meta.xml
<CustomField>
    <fullName>Innova_Description_of_the_Request__c</fullName>
    <label>Description of the Request</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Edit__c.field-meta.xml
<CustomField>
    <fullName>Innova_Edit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Edit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Foundational_access__c.field-meta.xml
<CustomField>
    <fullName>Innova_Foundational_access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Foundational Data Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Region__c.field-meta.xml
<CustomField>
    <fullName>Innova_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>APAC (India)</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>EMEA (Europe)</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Requires_IT_Approval__c.field-meta.xml
<CustomField>
    <fullName>Innova_Requires_IT_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires IT Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Innova_Brand__c.field-meta.xml
<CustomField>
    <fullName>Innova_Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Innova Solutions</fullName>
            </value>
            <value>
                <fullName>HireGenics</fullName>
            </value>
            <value>
                <fullName>Volt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Innova_Region__c.field-meta.xml
<CustomField>
    <fullName>Innova_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC (India)</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>EMEA (Europe)</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
                <isActive>false</isActive>
                <label>UK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationRequest.cls
public class ApplicationRequest {
  //@AuraEnabled is annotation enables LWC to access below apex method
  //(cacheable=true) is for caching the data on client side storage without waiting for server trips. Which imporves the performance
  @AuraEnabled(cacheable=true)
   public static List<Innova_Application_Software__c> getApplication(String searchKey,Integer pageNumber,String region,String brand) {
    String key = '%' + searchKey + '%'; 
    pageNumber= ((pageNumber-1)*15);
    List<User> currentUser =[Select Innova_Brand__c,Innova_Region__c FROM User WHERE Id= :UserInfo.getUserId()];
   List<Innova_Application_Software__c> SearchApplicationList= [select Id,Name,Innova_Add__c, Innova_Edit__c, Innova_Delete__c, Innova_Requires_IT_Approval__c, 
   Innova_Description_of_the_Request__c,Innova_Access_Level__c,Innova_Foundational_access__c  from Innova_Application_Software__c WHERE Name LIKE : key 
   
   AND Innova_Region__c = :region AND Innova_Brand__c = :brand
   Order by Name Asc OFFSET :pageNumber ];
   if(SearchApplicationList.size()>0){
    return SearchApplicationList;
  

   }
   return null;
 }

 @AuraEnabled(cacheable=true)
 public static List < customValueWrapper > pickListValueDynamically(sObject customObjInfo, string selectPicklistApi) {

  Schema.DescribeSObjectResult objDescribe = customObjInfo.getSObjectType().getDescribe();
  
  map < String, Schema.SObjectField > customFieldMap = objDescribe.fields.getMap();
  
  list < Schema.PicklistEntry > custPickValues = customFieldMap.get(selectPicklistApi).getDescribe().getPickListValues();
  
  list < customValueWrapper > customObjWrapper = new list < customValueWrapper > ();


  customValueWrapper blankOptionValueWrapper = new customValueWrapper();
  
  blankOptionValueWrapper.custFldlabel = '--None--';
  
  blankOptionValueWrapper.custFldvalue = '';
  
  customObjWrapper.add(blankOptionValueWrapper);


  
  for (Schema.PicklistEntry myCustPick: custPickValues) {
  
  customValueWrapper selectOptionValueWrapper = new customValueWrapper();
  
  selectOptionValueWrapper.custFldlabel = myCustPick.getLabel();
  
  selectOptionValueWrapper.custFldvalue = myCustPick.getValue();
  
  customObjWrapper.add(selectOptionValueWrapper);
  
  }
  
  return customObjWrapper;
  
  }
  
  // wrapper class
  
  public with sharing class customValueWrapper {
  
  @auraEnabled public string custFldlabel {get;set;}
  
@auraEnabled public string custFldvalue {get;set;}
  
  }
  
  }