force-app/main/default/objects/Innova_Application_Software__c/Innova_Application_Software__c.object-meta.xml
<CustomObject>
    <label>Applications/Software</label>
    <nameField>
        <label>Applications/Software Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications/Software</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Innova_Access_Level__c</fullName>
    <label>Access Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Add__c.field-meta.xml
<CustomField>
    <fullName>Innova_Add__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Delete__c.field-meta.xml
<CustomField>
    <fullName>Innova_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Description_of_the_Request__c.field-meta.xml
<CustomField>
    <fullName>Innova_Description_of_the_Request__c</fullName>
    <label>Description of the Request</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Edit__c.field-meta.xml
<CustomField>
    <fullName>Innova_Edit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Edit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Foundational_access__c.field-meta.xml
<CustomField>
    <fullName>Innova_Foundational_access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Foundational Data Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Innova_Application_Software__c/fields/Innova_Requires_IT_Approval__c.field-meta.xml
<CustomField>
    <fullName>Innova_Requires_IT_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires IT Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/newHireRequest.cls
public class newHireRequest {
    //@AuraEnabled is annotation enables LWC to access below apex method
    //(cacheable=true) is for caching the data on client side storage without waiting for server trips. Which imporves the performance
    @AuraEnabled(cacheable=true)
     public static List<Innova_Application_Software__c> getApplication(String searchKey,Integer pageNumber) {
      String key = '%' + searchKey + '%'; 
      pageNumber= ((pageNumber-1)*15);
      
     List<Innova_Application_Software__c> SearchApplicationList= [select Id,Name,Innova_Add__c, Innova_Edit__c, Innova_Delete__c, Innova_Requires_IT_Approval__c, Innova_Description_of_the_Request__c,Innova_Access_Level__c,Innova_Foundational_access__c  from Innova_Application_Software__c WHERE Name LIKE : key Order by Name Asc OFFSET :pageNumber ];
     if(SearchApplicationList.size()>0){
      return SearchApplicationList;
    
  
     }
     return null;
   }
  }