force-app/main/default/objects/Innova_ITSC_Task__c/Innova_ITSC_Task__c.object-meta.xml
<CustomObject>
    <description>ITSC Task object is created to track task assigned to Agent from Service request or other modules</description>
    <label>ITSC Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>ITSC Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ITSC Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Innova_ITSC_Task__c/fields/Innova_Status__c.field-meta.xml
<CustomField>
    <fullName>Innova_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PathControllerTask.cls
public with sharing class PathControllerTask {
    
    @AuraEnabled(cacheable=true)
    public static String getTaskStatusPath(Id taskId) {
        
        List<String> statusPath = new List<String>();
        
        for (Innova_ITSC_Task__c t : [SELECT Innova_Status__c FROM Innova_ITSC_Task__c WHERE Id = :taskId ]) {
            statusPath.add(t.Innova_Status__c);                              
        }
           return String.join(statusPath, ' > ');
    }

}