force-app/main/default/objects/Innova_ITSC_Task__c/Innova_ITSC_Task__c.object-meta.xml
<CustomObject>
    <description>ITSC Task object is created to track task assigned to Agent from Service request or other modules</description>
    <label>ITSC Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>ITSC Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ITSC Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Innova_ITSC_Task__c/fields/Case_Title__c.field-meta.xml
<CustomField>
    <fullName>Case_Title__c</fullName>
    <formula>Innova_Related_Case__r.Subject</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Innova_ITSC_Task__c/fields/Created_By_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Full_Name__c</fullName>
    <formula>CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created By Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Innova_ITSC_Task__c/fields/Innova_Status__c.field-meta.xml
<CustomField>
    <fullName>Innova_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Innova_ITSC_Task__c/fields/Innova_Subject__c.field-meta.xml
<CustomField>
    <fullName>Innova_Subject__c</fullName>
    <label>Task Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Innova_ITSC_Task__c/fields/Innova_Task_Notes__c.field-meta.xml
<CustomField>
    <fullName>Innova_Task_Notes__c</fullName>
    <label>Task Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/portalTaskController.cls
public class portalTaskController {

    @AuraEnabled
    public static String getTaskBannerData(String recordId){
        
        System.debug('recordId: ' + recordId);
        Innova_ITSC_Task__c t = [SELECT Name, Innova_Subject__c, Innova_Status__c,Created_By_Full_Name__c FROM Innova_ITSC_Task__c WHERE Id = :recordId LIMIT 1];
        
        if ( t == null ) return '[]'; 

        String name = t.Name != null ? t.Name : '';
        String status = t.Innova_Status__c != null ? t.Innova_Status__c : '';
        String subject = t.Innova_Subject__c  != null ? t.Innova_Subject__c : '';
        String createdByFullName = t.Created_By_Full_Name__c  != null ? t.Created_By_Full_Name__c : '';
            
        String returnValue = '[{"label":"Task #","value":"' + name + '"},{"label":"Status","value":"' + status + '"},{"label":"Subject","value":"' + subject + '"},{"label":"Created By","value":"' + createdByFullName + '"}]';
        System.debug('returnValue: ' + returnValue);    
        
        return returnValue;
        
    }
    
    @AuraEnabled
    public static String getTaskDetail(String recordId){
        
        System.debug('search for Task by Id: ' + recordId);
           
        Innova_ITSC_Task__c t = [SELECT Innova_Subject__c, Innova_Task_Notes__c, Case_Title__c FROM Innova_ITSC_Task__c WHERE Id = :recordId LIMIT 1];
            
        if( t == null ) return '[]';

        String subject = t.Innova_Subject__c != null ? t.Innova_Subject__c : '';
        String notes = t.Innova_Task_Notes__c != null ? t.Innova_Task_Notes__c : '';
        String caseTitle = t.Case_Title__c != null ? t.Case_Title__c : '';
        
        String returnValue = '[{"label":"Subject","value":"' + subject+ '"},{"label":"Notes","value":"' + notes + '"},{"label":"Case Title","value":"' + caseTitle + '"}]';
        System.debug('returnValue: ' + returnValue);
        
        return returnValue;
        
    }
    
    @AuraEnabled
    public static Innova_ITSC_Task__c getTask(String recordId){
        
        return [Select Innova_Subject__c from Innova_ITSC_Task__c Where Id = :recordId];
    }
}